
CREATE TABLE IF NOT EXISTS videos (
  id TEXT PRIMARY KEY,
  filename TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  video_id TEXT,
  variant TEXT NOT NULL,
  status TEXT DEFAULT 'QUEUED',  -- ENUM not strictly supported, using TEXT 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED'
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  meta TEXT DEFAULT '{}',
  FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE
);
